"use server"

import type { Question, QuestionType } from "@/lib/db/schema"
import { revalidatePath } from "next/cache"
import { EXAM_WEIGHTS } from "@/lib/chapters"

const seedQuestions: Omit<Question, "id" | "createdAt">[] = [
  { text: "Které dva výroky správně popisují cíle testování?", type: "multiple", options: ["Vyhodnotit pracovní produkty", "Snížit úroveň produktového rizika", "Dokázat, že software nemá vady", "Nahradit ladění", "Zaručit termín vydání"], correctIndices: [0, 1], explanation: "Testování hodnotí pracovní produkty a poskytuje informace ke snížení rizik; úplnou bezchybnost dokázat nemůže.", categoryId: 1 },
  { text: "Který princip testování říká, že opakování stejných testů postupně přestává odhalovat nové vady?", type: "single", options: ["Paradox pesticidu", "Shlukování vad", "Absence chyb je klam", "Testování závisí na kontextu"], correctIndices: [0], explanation: "Podle paradoxu pesticidu je nutné testy pravidelně revidovat a doplňovat.", categoryId: 1 },
  { text: "Jaký je vztah mezi testováním a laděním?", type: "single", options: ["Testování odhaluje selhání, ladění hledá a odstraňuje jejich příčiny", "Jde o dvě označení stejné činnosti", "Ladění provádí vždy tester", "Testování následuje až po ladění"], correctIndices: [0], explanation: "Dynamické testování může ukázat selhání; ladění lokalizuje, analyzuje a odstraňuje vadu.", categoryId: 1 },
  { text: "Jaký přínos má zapojení testerů do revize uživatelských příběhů v rané fázi životního cyklu vývoje?", type: "single", options: ["Včasné odhalení nejednoznačných požadavků", "Odstranění potřeby systémového testování", "Automatické schválení akceptačních kritérií", "Přenesení odpovědnosti za kvalitu na testery"], correctIndices: [0], explanation: "Včasné zapojení testerů pomáhá předcházet vadám dříve, než se promítnou do kódu.", categoryId: 2 },
  { text: "Které dvě činnosti podporují přístup DevOps?", type: "multiple", options: ["Průběžná integrace", "Průběžné doručování", "Oddělení vývoje a provozu", "Jednorázové testování před vydáním", "Ruční nasazení každé změny"], correctIndices: [0, 1], explanation: "DevOps typicky využívá průběžnou integraci a doručování se silnou automatizací.", categoryId: 2 },
  { text: "Který přístup k vývoji nejlépe podporuje princip posunu testování doleva?", type: "single", options: ["Provádění revizí a analýzy již nad ranými pracovními produkty", "Odložení všech testů na konec projektu", "Testování pouze v produkci", "Vyřazení testerů z plánování"], correctIndices: [0], explanation: "Posun doleva znamená zahájit testovací aktivity co nejdříve, například revizemi požadavků.", categoryId: 2 },
  { text: "Přiřaďte následující role (1–3) k jejich typickým úkolům v rámci statické analýzy (A–C):\n\n1. Autor\n2. Moderátor\n3. Zapisovatel\n\nA. Řídí průběh schůzky a zajišťuje dodržování pravidel.\nB. Zaznamenává nalezené defekty a rozhodnutí ze schůzky.\nC. Vytvořil zkoumaný pracovní produkt a opravuje v něm nalezené chyby.", type: "matching", options: ["1A, 2B, 3C", "1C, 2A, 3B", "1B, 2C, 3A", "1C, 2B, 3A"], correctIndices: [1], explanation: "Autor vytvořil dokument (1→C), moderátor vede schůzku (2→A) a zapisovatel pořizuje zápis (3→B).", categoryId: 3 },
  { text: "Jaký je hlavní rozdíl mezi statickým a dynamickým testováním?", type: "single", options: ["Statické testování nevyžaduje spuštění testovaného softwaru", "Statické testování provádí pouze vývojář", "Dynamické testování nepracuje s testovacími daty", "Dynamické testování nelze automatizovat"], correctIndices: [0], explanation: "Při statickém testování se pracovní produkt analyzuje bez spuštění jeho kódu.", categoryId: 3 },
  { text: "Přiřaďte techniky testování (1–3) k jejich charakteristikám (A–C):\n\n1. Rozdělení do tříd ekvivalence\n2. Testování větví\n3. Odhadování chyb\n\nA. Využívá zkušenosti testera a znalost častých vad.\nB. Rozděluje data do skupin se stejným očekávaným zpracováním.\nC. Odvozuje testy z řídicího toku programu.", type: "matching", options: ["1A, 2B, 3C", "1B, 2C, 3A", "1C, 2A, 3B", "1B, 2A, 3C"], correctIndices: [1], explanation: "Třídy ekvivalence seskupují data (1→B), větve vycházejí z řídicího toku (2→C) a odhadování chyb ze zkušenosti (3→A).", categoryId: 4 },
  { text: "Které dvě hodnoty jsou hraničními hodnotami platného intervalu 1 až 100?", type: "multiple", options: ["1", "100", "50", "60", "75"], correctIndices: [0, 1], explanation: "Platnými hranicemi intervalu jsou hodnoty 1 a 100.", categoryId: 4 },
  { text: "Tabulka rozhodnutí obsahuje tři binární podmínky. Kolik pravidel může mít úplná tabulka před odstraněním nemožných kombinací?", type: "single", options: ["8", "3", "6", "9"], correctIndices: [0], explanation: "Pro tři nezávislé binární podmínky existuje 2³, tedy osm kombinací.", categoryId: 4 },
  { text: "Co vyjadřuje produktové riziko?", type: "single", options: ["Možnost, že pracovní produkt nesplní oprávněné potřeby uživatelů", "Riziko překročení rozpočtu testovacího týmu", "Pravděpodobnost absence zápisu ze schůzky", "Počet testerů dostupných v projektu"], correctIndices: [0], explanation: "Produktové riziko souvisí s potenciálním selháním kvality produktu a jeho dopadem.", categoryId: 5 },
  { text: "Které dvě informace obvykle obsahuje kvalitní hlášení o vadě?", type: "multiple", options: ["Kroky k reprodukci", "Očekávaný a skutečný výsledek", "Soukromé hodnocení vývojáře", "Mzdové údaje týmu", "Nesouvisející obchodní údaje"], correctIndices: [0, 1], explanation: "Reprodukovatelné kroky a porovnání výsledků umožňují vadu analyzovat.", categoryId: 5 },
  { text: "Jak se obvykle určuje úroveň produktového rizika?", type: "single", options: ["Kombinací pravděpodobnosti a dopadu", "Pouze počtem testovacích případů", "Pouze délkou zdrojového kódu", "Počtem členů projektového týmu"], correctIndices: [0], explanation: "Úroveň rizika je funkcí pravděpodobnosti výskytu a závažnosti dopadu.", categoryId: 5 },
  { text: "Který ukazatel nejlépe podporuje sledování průběhu provádění testů?", type: "single", options: ["Počet provedených, úspěšných a neúspěšných testů", "Počet e-mailů v týmu", "Velikost kanceláře", "Počet řádků zápisu ze schůzky"], correctIndices: [0], explanation: "Stav provedení a výsledky testů přímo ukazují postup vůči plánu.", categoryId: 5 },
  { text: "Jaké je významné riziko automatizace testování?", type: "single", options: ["Nerealistická očekávání od přínosů nástroje", "Nástroj vždy zvýší počet ručních testů", "Automatizované testy nelze opakovat", "Nástroje znemožňují měření pokrytí"], correctIndices: [0], explanation: "Nástroj bez realistických očekávání, procesu a údržby může mít nízkou návratnost.", categoryId: 6 },
  { text: "Které dva přínosy mohou poskytnout nástroje pro testování?", type: "multiple", options: ["Opakovatelné provádění testů", "Objektivní měření pokrytí", "Zaručení bezvadného produktu", "Úplné nahrazení lidského úsudku", "Odstranění potřeby údržby testů"], correctIndices: [0, 1], explanation: "Nástroje podporují opakovatelnost a měření, ale nezaručují bezvadnost.", categoryId: 6 },
  { text: "Který faktor je nejdůležitější při zavádění nového testovacího nástroje?", type: "single", options: ["Pilotní ověření a vyhodnocení přínosů pro konkrétní prostředí", "Nákup nejdražší licence bez analýzy", "Okamžité zrušení všech ručních testů", "Výběr pouze podle vzhledu uživatelského rozhraní"], correctIndices: [0], explanation: "Pilotní projekt ověří vhodnost nástroje, náklady, přínosy i potřebné změny procesu.", categoryId: 6 },
]

const store = globalThis as typeof globalThis & { istqbQuestionsV4?: Question[] }
if (!store.istqbQuestionsV4) store.istqbQuestionsV4 = []
// Seedujeme pouze skutečně prázdné úložiště, takže restart modulu nevytváří kopie.
if (store.istqbQuestionsV4.length === 0) {
  store.istqbQuestionsV4.push(...seedQuestions.map((question, index) => ({ ...question, id: index + 1, createdAt: new Date(2026, 0, index + 1) })))
}
const data = () => store.istqbQuestionsV4!
const shuffle = <T,>(items: T[]) => { const result=[...items]; for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]} return result }
export async function getQuestionCount() { return data().length }
export async function getAllQuestions() { return [...data()].sort((a,b) => b.id-a.id) }
export async function getQuestion(id:number) { return data().find(question => question.id === id) ?? null }
export async function getQuestionsByChapters(ids: number[]) { return shuffle(data().filter(q => ids.includes(q.categoryId))).slice(0,40) }
export async function getFullExamQuestions(total = 40) { const exact=EXAM_WEIGHTS.map(w=>w*total);const counts=exact.map(Math.floor);exact.map((v,i)=>({i,f:v-counts[i]})).sort((a,b)=>b.f-a.f).slice(0,total-counts.reduce((s,c)=>s+c,0)).forEach(({i})=>counts[i]++);return shuffle(counts.flatMap((count,index)=>shuffle(data().filter(q=>q.categoryId===index+1)).slice(0,count))) }
export async function deleteQuestion(id:number) { store.istqbQuestionsV4=data().filter(q=>q.id!==id); revalidatePath("/admin") }
export async function deleteDuplicateQuestions() { const seen=new Set<string>();let removed=0;store.istqbQuestionsV4=data().filter(question=>{if(seen.has(question.text)){removed++;return false}seen.add(question.text);return true});revalidatePath("/admin");revalidatePath("/");return removed }
export type AddQuestionState={success?:boolean;error?:string}
function validate(value: unknown): Omit<Question,"id"|"createdAt"> { const q=value as Record<string,unknown>;const type=q.type as QuestionType;const count=Array.isArray(q.options)?q.options.length:0;if(typeof q.text!=="string"||!q.text.trim()||!["single","multiple","matching"].includes(type)||!Array.isArray(q.options)||count<4||count>5||!q.options.every(x=>typeof x==="string"&&x.trim())||!Array.isArray(q.correctIndices)||!q.correctIndices.every(x=>Number.isInteger(x)&&Number(x)>=0&&Number(x)<count)||typeof q.explanation!=="string"||!q.explanation.trim()||!Number.isInteger(q.categoryId)||Number(q.categoryId)<1||Number(q.categoryId)>6)throw new Error("Zkontrolujte prosím, zda jsou všechna pole správně vyplněná.");if(q.correctIndices.length===0)throw new Error("Vyberte prosím správnou odpověď.");if((type==="single"||type==="matching")&&q.correctIndices.length!==1)throw new Error("Otázka s jednou odpovědí musí mít právě jednu správnou možnost.");if(type==="multiple"&&q.correctIndices.length<2)throw new Error("Otázka s více odpověďmi musí mít alespoň dvě správné možnosti.");return{text:q.text.trim(),type,options:(q.options as string[]).map(x=>x.trim()),correctIndices:q.correctIndices as number[],explanation:q.explanation.trim(),categoryId:Number(q.categoryId)} }
function fromForm(formData:FormData){const type=String(formData.get("type")||"single") as QuestionType;const optionCount=type==="multiple"?5:4;return validate({text:String(formData.get("text")||""),type,options:Array.from({length:optionCount},(_,i)=>String(formData.get(`option-${i}`)||"")),correctIndices:formData.getAll("correctIndices").map(Number),explanation:String(formData.get("explanation")||""),categoryId:Number(formData.get("categoryId"))})}
export async function bulkImportQuestions(json:string):Promise<AddQuestionState>{try{const parsed=JSON.parse(json);if(!Array.isArray(parsed))return{error:"JSON musí obsahovat pole otázek."};const valid=parsed.map(validate);let next=Math.max(...data().map(q=>q.id),0)+1;data().unshift(...valid.map(q=>({...q,id:next++,createdAt:new Date()})));revalidatePath("/admin");revalidatePath("/");return{success:true}}catch(e){return{error:e instanceof Error?e.message:"JSON se nepodařilo zpracovat."}}}
export async function addQuestion(_state:AddQuestionState,formData:FormData):Promise<AddQuestionState>{try{const question=fromForm(formData);data().unshift({...question,id:Math.max(...data().map(x=>x.id),0)+1,createdAt:new Date()});revalidatePath("/admin");return{success:true}}catch(e){return{error:e instanceof Error?e.message:"Otázku nelze uložit."}}}
export async function updateQuestion(id:number, formData:FormData):Promise<AddQuestionState>{try{const question=fromForm(formData);const index=data().findIndex(item=>item.id===id);if(index<0)return{error:"Otázka nebyla nalezena."};data()[index]={...data()[index],...question};revalidatePath("/admin");revalidatePath(`/admin/edit/${id}`);revalidatePath("/");return{success:true}}catch(e){return{error:e instanceof Error?e.message:"Změny nelze uložit."}}}
