"use client"
import { useState, useTransition } from "react"
import type { Question } from "@/lib/db/schema"
import { bulkImportQuestions, deleteDuplicateQuestions, deleteQuestion } from "@/app/actions/questions"
import { AddQuestionForm } from "@/components/add-question-form"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Clipboard, Check, Pencil, Trash2, Upload } from "lucide-react"
import { toast } from "sonner"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { CHAPTERS, getChapterName } from "@/lib/chapters"

const example=`[\n  {\n    "text": "Které dva cíle patří mezi cíle testování?",\n    "type": "multiple",\n    "options": ["Odhalit vady", "Snížit riziko", "Dokázat bezchybnost", "Nahradit ladění", "Zrušit revize"],\n    "correctIndices": [0, 1],\n    "explanation": "Testování odhaluje vady a snižuje riziko.",\n    "categoryId": 1\n  }\n]`
export function AdminDashboard({questions}:{questions:Question[]}){const[tab,setTab]=useState("list");const[json,setJson]=useState("");const[chapter,setChapter]=useState(1);const[copied,setCopied]=useState(false);const[pending,start]=useTransition();const router=useRouter();
 const existing=questions.map(question=>`- ${question.text}`).join("\n")||"- V této kapitole zatím nejsou žádné otázky."
 const prompt=`Vygeneruj mi balík 30 testovacích otázek pro zkoušku ISTQB Foundation Level (v4.0) z ${CHAPTERS[chapter-1]}. Otázky musí být v češtině. Zahrň mix 'single' (klasické 1 ze 4), 'multiple' (více správných) a přiřazovacích otázek. U přiřazovací otázky zapiš položky 1, 2, 3 a definice A, B, C do textu na samostatné řádky pomocí znaků \\n; čtyři možnosti budou úplné kombinace (např. ‚1A, 2B, 3C‘), správná bude právě jedna a typ v JSON bude 'single'.
VÝSTUP POSKYTNI POUZE JAKO VALIDNÍ JSON POLE. Formát: { 'text': 'Text otázky (použij \\n pro odřádkování u přiřazovacích otázek)', 'type': 'single' | 'multiple', 'options': ['A', 'B', 'C', 'D'], 'correctIndices': [0], 'explanation': 'Zdůvodnění', 'categoryId': ${chapter} }.
DŮLEŽITÉ: Níže je seznam otázek, které už v databázi MÁM. Vygeneruj ZCELA NOVÉ otázky a neopakuj tato témata a znění:
${existing}`
 const removeDuplicates=()=>start(async()=>{const count=await deleteDuplicateQuestions();toast.success(`Odstraněno duplicitních otázek: ${count}.`);router.refresh()})
 const importData=()=>start(async()=>{const result=await bulkImportQuestions(json);result.error?toast.error(result.error):(toast.success("Otázky byly úspěšně importovány."),setJson(""),router.refresh())})
 return <div className="mt-8"><div className="grid grid-cols-3 rounded-xl bg-muted p-1">{[["list","Seznam otázek"],["add","Přidat ručně"],["bulk","Hromadný import"]].map(([id,label])=><button key={id} className={`rounded-lg px-2 py-3 text-sm font-semibold ${tab===id?"bg-card shadow-sm":"text-muted-foreground"}`} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==="list"&&<div className="mt-6"><div className="mb-4 flex justify-end"><Button variant="outline" disabled={pending} onClick={removeDuplicates}><Trash2/>Odstranit duplicitní otázky</Button></div><div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full text-left"><thead className="bg-muted text-sm"><tr><th className="p-4">Otázka</th><th className="p-4">Typ</th><th className="p-4">Kapitola</th><th className="p-4 text-right">Akce</th></tr></thead><tbody>{questions.map(q=><tr key={q.id} className="border-t"><td className="min-w-72 p-4">{q.text}</td><td className="p-4 text-sm">{q.type==="single"?"Jedna odpověď":"Více odpovědí"}</td><td className="min-w-64 p-4">{getChapterName(q.categoryId)}</td><td className="p-4 text-right"><div className="flex justify-end gap-2"><Button asChild variant="outline" size="sm"><Link href={`/admin/edit/${q.id}`}><Pencil/>Upravit</Link></Button><Button variant="outline" size="sm" onClick={()=>start(async()=>{await deleteQuestion(q.id);router.refresh()})}><Trash2/>Smazat</Button></div></td></tr>)}</tbody></table></div></div>}
 {tab==="add"&&<div className="mt-6"><AddQuestionForm/></div>}
 {tab==="bulk"&&<div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-xl border bg-card p-5"><h2 className="text-xl font-bold">Hromadný import JSON</h2><p className="mt-1 text-sm text-muted-foreground">Vložte validní pole otázek ve formátu níže.</p><Textarea value={json} onChange={e=>setJson(e.target.value)} rows={14} className="mt-4 font-mono" placeholder="Sem vložte pole JSON…"/><Button className="mt-4" disabled={pending||!json.trim()} onClick={importData}><Upload/> {pending?"Importuji…":"Importovat"}</Button></section><div className="space-y-6"><section className="rounded-xl border bg-slate-950 p-5 text-slate-100"><h2 className="mb-3 font-bold">Ukázkový formát JSON</h2><pre className="overflow-x-auto text-xs leading-relaxed"><code>{example}</code></pre></section><section className="rounded-xl border border-primary/30 bg-accent/40 p-5"><h2 className="text-xl font-bold">Generátor zadání pro AI</h2><label className="mt-3 block text-sm font-semibold">Kapitola</label><Select value={chapter} onValueChange={value=>{setChapter(Number(value));setCopied(false)}}><SelectTrigger className="mt-2 w-full bg-background"><SelectValue/></SelectTrigger><SelectContent>{CHAPTERS.map((name,index)=><SelectItem key={name} value={index+1}>{name}</SelectItem>)}</SelectContent></Select><p className="mt-3 text-sm text-muted-foreground">Zadání automaticky obsahuje všechny existující otázky, aby se neopakovaly.</p><Textarea readOnly value={prompt} rows={16} className="mt-4 bg-background font-mono text-xs"/><Button variant="outline" className="mt-3" onClick={async()=>{await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?<Check/>:<Clipboard/>}{copied?"Zkopírováno":"Kopírovat zadání"}</Button></section></div></div>}</div>}
