"use client"
import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import type { Question } from "@/lib/db/schema"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import { cn } from "@/lib/utils"
import { getChapterName } from "@/lib/chapters"
import { ArrowLeft, ArrowRight, Clock3, Flag, Trophy, RotateCcw, Lightbulb } from "lucide-react"

type Answer=number[]
const same=(a:Answer,b:Answer)=>[...a].sort().join(",")===[...b].sort().join(",")
export function Quiz({questions:source,mode}:{questions:Question[];mode:string}){
 const questions=source;const[current,setCurrent]=useState(0);const[answers,setAnswers]=useState<Record<number,Answer>>({});const[flags,setFlags]=useState<number[]>([]);const[screen,setScreen]=useState<"quiz"|"review"|"result">("quiz");const[seconds,setSeconds]=useState(3600)
 useEffect(()=>{if(mode!=="quick"||screen!=="quiz")return;const timer=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(timer)},[mode,screen])
 const submit=useCallback(()=>setScreen("result"),[])
 useEffect(()=>{if(mode==="quick"&&seconds===0&&screen!=="result")submit()},[seconds,mode,screen,submit])
 const shuffled=useMemo(()=>Object.fromEntries(questions.map(q=>[q.id,q.options.map((text,index)=>({text,index})).sort(()=>Math.random()-.5)])),[questions])
 const score=questions.filter(q=>same(answers[q.id]||[],q.correctIndices)).length;const percent=Math.round(score/questions.length*100)
 if(screen==="result")return <main className="mx-auto min-h-svh max-w-3xl px-4 py-12"><section className="text-center"><Trophy className={cn("mx-auto size-16",percent>=65?"text-success":"text-error")}/><p className="mt-5 text-sm font-semibold uppercase text-muted-foreground">Váš konečný výsledek</p><h1 className="mt-1 text-6xl font-bold">{percent} %</h1><p className={cn("mt-3 text-xl font-semibold",percent>=65?"text-success":"text-error")}>{percent>=65?"Úspěšně splněno":"Test nebyl splněn"}</p><p className="mt-2 text-muted-foreground">Správně {score} z {questions.length}. Hranice úspěšnosti je 65 %.</p></section><h2 className="mt-10 text-2xl font-bold">Kontrola všech odpovědí</h2><div className="mt-4 space-y-4">{questions.map((q,i)=><article key={q.id} className="rounded-xl border bg-card p-5"><p className="font-semibold">{i+1}. {q.text}</p><p className={cn("mt-2 text-sm font-medium",same(answers[q.id]||[],q.correctIndices)?"text-success":"text-error")}>{same(answers[q.id]||[],q.correctIndices)?"Správná odpověď":"Nesprávná odpověď"}</p><div className="mt-3 flex gap-2 text-sm text-muted-foreground"><Lightbulb className="size-4 shrink-0 text-primary"/><p>{q.explanation}</p></div></article>)}</div><div className="mt-8 flex gap-3"><Button onClick={()=>location.reload()}><RotateCcw/>Zkusit znovu</Button><Button asChild variant="outline"><Link href="/">Zpět domů</Link></Button></div></main>
 if(screen==="review")return <main className="mx-auto min-h-svh max-w-3xl px-4 py-12"><h1 className="text-3xl font-bold">Kontrola před odevzdáním</h1><p className="mt-2 text-muted-foreground">Zkontrolujte zodpovězené, nezodpovězené a označené otázky.</p><div className="mt-6 flex flex-wrap gap-4 text-sm"><span><i className="mr-2 inline-block size-3 bg-primary"/>Zodpovězeno</span><span><i className="mr-2 inline-block size-3 bg-muted"/>Nezodpovězeno</span><span><i className="mr-2 inline-block size-3 bg-yellow-400"/>Označeno k revizi</span></div><div className="mt-6 grid grid-cols-5 gap-3 sm:grid-cols-8 md:grid-cols-10">{questions.map((q,i)=><button key={q.id} onClick={()=>{setCurrent(i);setScreen("quiz")}} className={cn("aspect-square rounded-md border text-sm font-bold",flags.includes(q.id)?"border-yellow-500 bg-yellow-300 text-yellow-950":answers[q.id]?.length?"border-primary bg-primary text-primary-foreground":"bg-muted")}>{i+1}</button>)}</div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button variant="outline" onClick={()=>setScreen("quiz")}><ArrowLeft/>Vrátit se k otázkám</Button><Button onClick={submit}>Odevzdat test</Button></div></main>
 const q=questions[current], selected=answers[q.id]||[], required=q.correctIndices.length
 const choose=(idx:number)=>setAnswers(a=>({...a,[q.id]:q.type==="single"?[idx]:selected.includes(idx)?selected.filter(x=>x!==idx):selected.length<required?[...selected,idx]:selected}))
 return <main className="mx-auto flex min-h-svh max-w-3xl flex-col px-4 py-6"><header className="mb-6"><div className="mb-3 flex items-center justify-between"><Button asChild variant="ghost" size="sm"><Link href="/"><ArrowLeft/>Ukončit</Link></Button>{mode==="quick"&&<span className={cn("flex items-center gap-2 font-mono font-bold",seconds<300&&"text-error")}><Clock3 className="size-4"/>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</span>}<span className="text-sm text-muted-foreground">Otázka {current+1} z {questions.length}</span></div><Progress value={(current+1)/questions.length*100}/></header><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-primary">{getChapterName(q.categoryId)}</p><h1 className="mt-2 text-xl font-semibold sm:text-2xl">{q.text}</h1><p className="mt-2 text-sm text-muted-foreground">{q.type==="multiple"?`Vyberte přesně ${required} správné odpovědi.`:"Vyberte právě jednu správnou odpověď."}</p></div><Button variant={flags.includes(q.id)?"default":"outline"} size="sm" onClick={()=>setFlags(f=>f.includes(q.id)?f.filter(x=>x!==q.id):[...f,q.id])}><Flag/> <span className="hidden sm:inline">Označit k revizi</span></Button></div><div className="mt-6 space-y-3">{shuffled[q.id].map((o:{text:string,index:number},i:number)=><label key={o.index} className={cn("flex cursor-pointer items-center gap-3 rounded-xl border-2 bg-card p-4",selected.includes(o.index)&&"border-primary bg-accent")}><input className="size-4 accent-primary" type={q.type==="single"?"radio":"checkbox"} name={`otazka-${q.id}`} checked={selected.includes(o.index)} onChange={()=>choose(o.index)}/><span className="flex size-7 shrink-0 items-center justify-center rounded bg-muted text-sm font-bold">{String.fromCharCode(65+i)}</span><span>{o.text}</span></label>)}</div><footer className="mt-auto flex justify-between gap-3 pt-8"><Button variant="outline" disabled={!current} onClick={()=>setCurrent(i=>i-1)}><ArrowLeft/>Předchozí</Button>{current<questions.length-1?<Button onClick={()=>setCurrent(i=>i+1)}>Další<ArrowRight/></Button>:<Button onClick={()=>setScreen("review")}>Zkontrolovat test<ArrowRight/></Button>}</footer></main>
}
